# Supabase connection configuration
[connections.supabase]
SUPABASE_URL = "https://eqyrpsmcujrbmskpwnlz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxeXJwc21jdWpyYm1za3B3bmx6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MDk5NjQsImV4cCI6MjA3MjI4NTk2NH0.mf8n__NtBiJj9ZKOQrkFX8HWP4ZvgFyBdNgPIKtydoI"